### PR TITLE
Change some button dimensions

### PR DESCRIPTION
**Pull request by probicheaux**

### CODE REVIEW

**Review by williambertrand — APPROVED** [review]
Ok to merge this as it's an improvement, but as a heads up, I think one thing we'll want to do pretty asap-y is make a common `<Button>` component that just wraps these `TouchableOpacity`'s with this style, and that way any button across the app uses the same style

**Comment by probicheaux** [comment]
> Ok to merge this as it's an improvement, but as a heads up, I think one thing we'll want to do pretty asap-y is make a common `<Button>` component that just wraps these `TouchableOpacity`'s with this style, and that way any button across the app uses the same style

Agree but the problem is that the sizes defined in other style sheets were too small to use here. Idk how to fix that. I also don't know if/how react supports altering StyleSheet objects

**Comment by williambertrand** [comment]
> 

ah ok so this was just a one-off for these button specifically to look different from other buttons? From a UI perspective, any time you need to differ from other buttons you should be able to answer the question of "what is important about these buttons looking different than other buttons in the app?" Which will almost always a way to just be like "ok let's just keep these buttons looking the same as other buttons"

**Comment by probicheaux** [comment]
> > 
> 
> ah ok so this was just a one-off for these button specifically to look different from other buttons? From a UI perspective, any time you need to differ from other buttons you should be able to answer the question of "what is important about these buttons looking different than other buttons in the app?" Which will almost always a way to just be like "ok let's just keep these buttons looking the same as other buttons"

Yeah I guess, but does that mean I should just make the text smaller?

**Pull request merged**
